github/workflows/build.yml
name: Build Salaa Editor EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller pyqt5 moviepy

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed salaa_editor.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SalaaEditorEXE
          path: dist/salaa_editor.exe
